version: "3.8"
services:
  app:
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - "db"

  db:
    image: postgres
    environment:
       POSTGRES_HOST: localhost
       POSTGRES_PORT: 5432
       POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data/

volumes:
  data:
